### PR TITLE
readme - added notes on how to run in OpenShift

### PR DESCRIPTION
**Pull request by alikrubin**

### CODE REVIEW

**Comment by vadimtk** [comment]
@alikrubin Do we want to allow root user for OpenShift deployments?
I thought the preferable use case is to run without root privileges.

**Comment by timvaillancourt** [comment]
@vadimtk the operator doesn't need for root for any reason and we should avoid it for security

**Comment by alikrubin** [comment]
Yes, I agree, the problem is here: 
`Warning   FailedCreate        statefulset-controller   create Pod my-cluster-name-rs0-0 in StatefulSet my-cluster-name-rs0 failed error: pods "my-cluster-name-rs0-0" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 1001: must be in the ranges: [1000150000, 1000159999]]`

`pkg/stub/psmdb.go:      defaultRunUID                   int64   = 1000160001
pkg/stub/psmdb.go:      if spec.RunUID == 0 {
pkg/stub/psmdb.go:              spec.RunUID = defaultRunUID
pkg/apis/psmdb/v1alpha1/types.go:       RunUID   int64          `json:"runUid,omitempty"`

**Comment by delgod** [comment]
@alikrubin, I believe we need to fix this issue on our side, not on openshift side.

**Pull request closed without merging**
